Music
paulwedeck/settlers-remake pull request #3
Opened 2021-01-10 19:24 UTC by Marvi-Marv

Hey Paul, in case you like the s3 music, you may want my implementation :) thanks for your contribution to the project

2021-01-11 18:57 UTC, paulwedeck requested changes
Thank you for writing this pr.
I would like to have the original music in jsettlers but I didn't find the time yet.
Also I only have the gold edition and that saves the music on the cd itself as audio tracks, so the only real way for me to test your pr is if you allow custom sound folders too.
I think you should look at extending SoundPlayer and mirror the structure of SoundManager and BackgroundSound, so that your code fits better into the overall project.

2021-01-11 18:57 UTC, paulwedeck commented on build.gradle
> +            /*add music dependencies
These dependencies are only relevent for swing. So this belongs in go.graphics.swing

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.common/src/main/java/jsettlers/common/music/MusicManager.java
> +			// throw new Exception("invalid music folder");
In this case we might aswell just play all the existing files that we can interpret

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.common/src/main/java/jsettlers/common/music/MusicManager.java
> +		if (MusicManager.lookupPath != null) {
This should really be a member function.

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.common/src/main/java/jsettlers/common/music/MusicManager.java
> +		List<String> list = new ArrayList<String>();
Why not just create Files here?

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.common/src/main/java/jsettlers/common/music/MusicPlayer.java
> +public final class MusicPlayer {
This class is basically a duplicate of SwingSoundPlayer except that the latter takes offsets into s3 sound file and this one takes ordinary sound files.

You might aswell merge the two.

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.common/src/main/java/jsettlers/common/music/MusicThread.java
> +	public MusicThread(final MusicPlayer musicPlayer, final int volume, final String musicFilePath, final String musicFileType, final String[] musicTracks) {
You might aswell just merge this class and MusicManager.

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.logic/src/main/java/jsettlers/input/GuiInterface.java
> +		MusicManager.startMusicThread(player.getCivilisation(), false);
This does not belong here. I would rather put this into MapContent

2021-01-11 18:57 UTC, paulwedeck commented on jsettlers.logic/src/main/java/jsettlers/input/GuiInterface.java
> +				MusicManager.stopMusicThread();
This should go into MapContent#stop()

2021-01-11 19:09 UTC, Marvi-Marv commented
> Thank you for writing this pr.
> I would like to have the original music in jsettlers but I didn't find the time yet.
> Also I only have the gold edition and that saves the music on the cd itself as audio tracks, so the only real way for me to test your pr is if you allow custom sound folders too.
> I think you should look at extending SoundPlayer and mirror the structure of SoundManager and BackgroundSound, so that your code fits better into the overall project.

Thank you for your feedback Paul. I will try to the code as much as possible in order to have a better fit for the overall project. You could create a new folder ("MUSIC" or "Theme") in your s3 install directory and copy the cd audio files there.
I am currently working on correcting the building images and ressource requirements for all civilizations.

2021-01-11 19:16 UTC, paulwedeck commented
> I am currently working on correcting the building images and ressource requirements for all civilizations.
Great to hear that.
If you haven't noticed already: The buildings are mostly defined in xml files in jsettlers.common/src/main/resources/jsettlers/common/buildings/
Also the BuildingCreatorApp in jsettlers.buildingcreator should be helpful.
There are also some tests that validate these xml files.

2021-01-11 19:22 UTC, Marvi-Marv commented
> > I am currently working on correcting the building images and ressource requirements for all civilizations.
> 
> Great to hear that.
> If you haven't noticed already: The buildings are mostly defined in xml files in jsettlers.common/src/main/resources/jsettlers/common/buildings/
> Also the BuildingCreatorApp in jsettlers.buildingcreator should be helpful.
> There are also some tests that validate these xml files.

Yes, i have already found these. And the tools are very helpful. I will push the first changes to my repository branch "AssignCorrectBuildingRessources" later this evening. I am still not entirley sure how i can transform the winegrower to the brewery for instance, but i am fine with the images and the ressources. Do you use some kind of messenger or voice tool in order to communicate?

2021-01-11 19:29 UTC, paulwedeck commented
You should look at the jobs for the backery. They should be much closer to the Brewery than the vineyard is.
You also shouldn't "transform" one kind of building to another but create a new entry in EBuildingType, etc. for it.
Its not an issue if there isn't a vineyard xml for the egyptians or a brewery for the romans.
We have a discord server. Its at the bottom of the readme. https://discord.gg/2hVV4u6

2021-01-22 14:26 UTC, Marvi-Marv commented
added gui and moved files to fit project structure

2021-06-26 14:41 UTC, closed without merging